### ISSUE TITLE
Comments about prototype-1-1

### ISSUE THREAD

**Issue by YounesN** [WSU-Capstone-2017/GOMC-Website#22]
The scheme of the website looks good but overall needs lots of work.
**GOMC.html**:
1. The white line under the menu is crossing the logo
2. The logo is too small
3. The menu is small
4. The disk logo above project title should be  removed
5. White text on Gray doesn't look good
6. We liked the announcement section where the important stuff is right in the middle of the page and hard to miss.

**Feature page missing**

**download.html**:
1. Everything has to change on this page, we don't like the old format. 

**documentation.html**:
1. It is missing XML generator
2. And perhaps a link to a youtube page? (a random one for now)
3. We might have some highlight tutorials but we also need a longer list of tutorials, as we will have more than 3 tutorials.

**publications.html**:
Not so bad, although formatting can be improved

**about.html**:
1. The width of Grant section and people section are different!!

**_General but important comments_**:
1. It is really important to test the website in different resolutions, the texts are small in larger screens.
2. We were happy about the color scheme and how clean the website looks
3. The page menu and footer needs to be consistent throughout the website.

**Comment by latimercaleb** [comment]
I've made a personal list of this feedback, other issues will be opened soon with feedback that hasn't been added yet. Closing this issue for now
