### ISSUE TITLE
Comments about prototype-1-2

### ISSUE THREAD

**Issue by YounesN** [WSU-Capstone-2017/GOMC-Website#23]
**General comments but important**
1. Same as prototype 1.1: the elements (pictures, headers, menu) seems way bigger than the text. Try to use % as much as you can. Definitely use "em" instead of "px". Take a look at this link:
`https://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/`
2. 

**gomc.html**
1. Logo color
2. Menu should not be larger than some fixed size, in larger screen they look really big.
3. Maybe a different carousel? The black sides kind of ruins it.

**publications.html**
looks good

**tutorial.html**
same comments as prototype1-1

**download.html**
1. maybe move the GOMC section to front page or features? Download page shouldn't have any description about the project

**feature.html**
1. again size problem

**about.html**
1. remove the border from people
2. Grants: logos are different size
3. Contact Us: we liked the idea of having a link to our github page, but maybe move it to download page?

**Comment by latimercaleb** [comment]
Same as feedback from Prototype-1-1. 

All feedback is noted, I will make issues for other these problems that are still in play with our current system
