### ISSUE TITLE
Site Map Fix

### ISSUE THREAD

**Issue by latimercaleb** [WSU-Capstone-2017/GOMC-Website#26]
### **Issue**

Site Map is not set up properly there need to be some changes

### **Expected Fix**

-  Multi-panel must be removed
- Single well must contain the following:
    * Custom styling
    * Tree structure of all internal pages
    * Each page name must link to itself
    * Each nav-bar page must be a parent in the tree, each link within that page must be a child

**Comment by muamer67** [comment]
Done?

**Comment by latimercaleb** [comment]
Why a question mark?

**Comment by muamer67** [comment]
Just for u to check out what I did on site map

**Comment by latimercaleb** [comment]
OK I have a couple of questions. Hop on slack when ya can.
