### ISSUE TITLE
Proto 1 feedback implementation

### ISSUE THREAD

**Issue by latimercaleb** [WSU-Capstone-2017/GOMC-Website#29]
### **Issue**
Proto-one has a good clean color scheme

### **Expected Fix**
- Implement feedback from the UI to the current scheme, have a simpler color pallete with the CSS
- Modify the CSS to have less complex colors, make things lighter and closer to white

**Comment by muamer67** [comment]
Added a more clean color scheme but will keep issue till menu nav bar is changed

**Comment by latimercaleb** [comment]
Nav-bar resolved, please pull the following commit:

https://github.com/WSU-Capstone-2017/GOMC-Website/commit/dcc9ee92ede4eefe39d8554dc16144ffbbe7e2b8

**Comment by latimercaleb** [comment]
@muamer67 isn't this resolved?

**Comment by latimercaleb** [comment]
This is done
