### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by latimercaleb** [WSU-Capstone-2017/GOMC-Website#32]
### **Issue**
Anticipate a longer list of features, adjustments need to be made

### **Expected Fix**
Make each feature smaller 1x3 row of tiles
Each feature should have an image, header,and text description

**Comment by muamer67** [comment]
So for this bug, is he saying he wants like 3 different cards on same rows each of them having a header on top of the image but where is the text description of it going to fit? Where should I put it, on the side of the image or under it?

**Comment by latimercaleb** [comment]
No he said that he wants the images smaller and a design that will make sense for multiple images. I am deciding to use tiles because they make sense for groups of smaller homogenous content. 

Card is the wrong word there, it should be tiles

Check out this guideline from material design, it doesn't need to do *exactly* what they have but it needs to match our need for the page

https://material.io/guidelines/components/grid-lists.html#grid-lists-content

**Comment by muamer67** [comment]
Done
